/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateTaskForm: typeof import('./src/components/CreateTaskForm.vue')['default']
    CreateTodoForm: typeof import('./src/components/CreateTodoForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TaskItemCard: typeof import('./src/components/TaskItemCard.vue')['default']
    TaskItemsList: typeof import('./src/components/TaskItemsList.vue')['default']
    TasksList: typeof import('./src/components/TasksList.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
